/**
 * 3gpp-iptvconfiguration
 * API for IPTV configuration. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AccessRightStatus.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

AccessRightStatus::AccessRightStatus() {}

void AccessRightStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool AccessRightStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AccessRightStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AccessRightStatus" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool AccessRightStatus::operator==(const AccessRightStatus& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool AccessRightStatus::operator!=(const AccessRightStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AccessRightStatus& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, AccessRightStatus& o) {
  from_json(j, o.m_value);
}

AccessRightStatus_anyOf AccessRightStatus::getValue() const {
  return m_value;
}

void AccessRightStatus::setValue(AccessRightStatus_anyOf value) {
  m_value = value;
}

AccessRightStatus_anyOf::eAccessRightStatus_anyOf
AccessRightStatus::getEnumValue() const {
  return m_value.getValue();
}

void AccessRightStatus::setEnumValue(
    AccessRightStatus_anyOf::eAccessRightStatus_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
