/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AccuracyFulfilmentIndicator.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

AccuracyFulfilmentIndicator::AccuracyFulfilmentIndicator() {}

void AccuracyFulfilmentIndicator::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool AccuracyFulfilmentIndicator::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AccuracyFulfilmentIndicator::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AccuracyFulfilmentIndicator" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool AccuracyFulfilmentIndicator::operator==(
    const AccuracyFulfilmentIndicator& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool AccuracyFulfilmentIndicator::operator!=(
    const AccuracyFulfilmentIndicator& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AccuracyFulfilmentIndicator& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, AccuracyFulfilmentIndicator& o) {
  from_json(j, o.m_value);
}

AccuracyFulfilmentIndicator_anyOf AccuracyFulfilmentIndicator::getValue()
    const {
  return m_value;
}

void AccuracyFulfilmentIndicator::setValue(
    AccuracyFulfilmentIndicator_anyOf value) {
  m_value = value;
}

AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf
AccuracyFulfilmentIndicator::getEnumValue() const {
  return m_value.getValue();
}

void AccuracyFulfilmentIndicator::setEnumValue(
    AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf
        value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
