/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AccuracyFulfilmentIndicator_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

AccuracyFulfilmentIndicator_anyOf::AccuracyFulfilmentIndicator_anyOf() {}

void AccuracyFulfilmentIndicator_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool AccuracyFulfilmentIndicator_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AccuracyFulfilmentIndicator_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AccuracyFulfilmentIndicator_anyOf" : pathPrefix;

  if (m_value ==
      AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool AccuracyFulfilmentIndicator_anyOf::operator==(
    const AccuracyFulfilmentIndicator_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool AccuracyFulfilmentIndicator_anyOf::operator!=(
    const AccuracyFulfilmentIndicator_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AccuracyFulfilmentIndicator_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf::
        FULFILLED:
      j = "REQUESTED_ACCURACY_FULFILLED";
      break;
    case AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf::
        NOT_FULFILLED:
      j = "REQUESTED_ACCURACY_NOT_FULFILLED";
      break;
  }
}

void from_json(const nlohmann::json& j, AccuracyFulfilmentIndicator_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "REQUESTED_ACCURACY_FULFILLED") {
    o.setValue(AccuracyFulfilmentIndicator_anyOf::
                   eAccuracyFulfilmentIndicator_anyOf::FULFILLED);
  } else if (s == "REQUESTED_ACCURACY_NOT_FULFILLED") {
    o.setValue(AccuracyFulfilmentIndicator_anyOf::
                   eAccuracyFulfilmentIndicator_anyOf::NOT_FULFILLED);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_"
          "anyOf";
    throw std::invalid_argument(ss.str());
  }
}

AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf
AccuracyFulfilmentIndicator_anyOf::getValue() const {
  return m_value;
}
void AccuracyFulfilmentIndicator_anyOf::setValue(
    AccuracyFulfilmentIndicator_anyOf::eAccuracyFulfilmentIndicator_anyOf
        value) {
  m_value = value;
}

}  // namespace oai::nef::model
