/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AmfEventType.h
 *
 *
 */

#ifndef AmfEventType_H_
#define AmfEventType_H_

#include <nlohmann/json.hpp>

#include "AmfEventType_anyOf.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class AmfEventType {
 public:
  AmfEventType();
  virtual ~AmfEventType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AmfEventType& rhs) const;
  bool operator!=(const AmfEventType& rhs) const;

  /////////////////////////////////////////////
  /// AmfEventType members

  AmfEventType_anyOf getValue() const;
  void setValue(AmfEventType_anyOf value);
  AmfEventType_anyOf::eAmfEventType_anyOf getEnumValue() const;
  void setEnumValue(AmfEventType_anyOf::eAmfEventType_anyOf value);
  friend void to_json(nlohmann::json& j, const AmfEventType& o);
  friend void from_json(const nlohmann::json& j, AmfEventType& o);
  friend void to_json(nlohmann::json& j, const AmfEventType_anyOf& o);
  friend void from_json(const nlohmann::json& j, AmfEventType_anyOf& o);

 protected:
  AmfEventType_anyOf m_value;
};

}  // namespace oai::nef::model

#endif /* AmfEventType_H_ */
