/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AppDescriptor.h
 *
 *
 */

#ifndef AppDescriptor_H_
#define AppDescriptor_H_

#include <map>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class AppDescriptor {
 public:
  AppDescriptor();
  virtual ~AppDescriptor() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const AppDescriptor& rhs) const;
  bool operator!=(const AppDescriptor& rhs) const;

  /////////////////////////////////////////////
  /// AppDescriptor members

  /// <summary>
  ///
  /// </summary>
  std::string getOsId() const;
  void setOsId(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  std::map<std::string, std::string> getAppIds() const;
  void setAppIds(std::map<std::string, std::string> const& value);

  friend void to_json(nlohmann::json& j, const AppDescriptor& o);
  friend void from_json(const nlohmann::json& j, AppDescriptor& o);

 protected:
  std::string m_OsId;

  std::map<std::string, std::string> m_AppIds;
};

}  // namespace oai::nef::model

#endif /* AppDescriptor_H_ */
