/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AssociationType_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

AssociationType_anyOf::AssociationType_anyOf() {}

void AssociationType_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool AssociationType_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AssociationType_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "AssociationType_anyOf" : pathPrefix;

  if (m_value == AssociationType_anyOf::eAssociationType_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool AssociationType_anyOf::operator==(const AssociationType_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool AssociationType_anyOf::operator!=(const AssociationType_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AssociationType_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case AssociationType_anyOf::eAssociationType_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case AssociationType_anyOf::eAssociationType_anyOf::IMEI:
      j = "IMEI";
      break;
    case AssociationType_anyOf::eAssociationType_anyOf::IMEISV:
      j = "IMEISV";
      break;
  }
}

void from_json(const nlohmann::json& j, AssociationType_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "IMEI") {
    o.setValue(AssociationType_anyOf::eAssociationType_anyOf::IMEI);
  } else if (s == "IMEISV") {
    o.setValue(AssociationType_anyOf::eAssociationType_anyOf::IMEISV);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " AssociationType_anyOf::eAssociationType_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

AssociationType_anyOf::eAssociationType_anyOf AssociationType_anyOf::getValue()
    const {
  return m_value;
}
void AssociationType_anyOf::setValue(
    AssociationType_anyOf::eAssociationType_anyOf value) {
  m_value = value;
}

}  // namespace oai::nef::model
