/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * CnType.h
 *
 *
 */

#ifndef CnType_H_
#define CnType_H_

#include <nlohmann/json.hpp>

#include "CnType_anyOf.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class CnType {
 public:
  CnType();
  virtual ~CnType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const CnType& rhs) const;
  bool operator!=(const CnType& rhs) const;

  /////////////////////////////////////////////
  /// CnType members

  CnType_anyOf getValue() const;
  void setValue(CnType_anyOf value);
  CnType_anyOf::eCnType_anyOf getEnumValue() const;
  void setEnumValue(CnType_anyOf::eCnType_anyOf value);
  friend void to_json(nlohmann::json& j, const CnType& o);
  friend void from_json(const nlohmann::json& j, CnType& o);
  friend void to_json(nlohmann::json& j, const CnType_anyOf& o);
  friend void from_json(const nlohmann::json& j, CnType_anyOf& o);

 protected:
  CnType_anyOf m_value;
};

}  // namespace oai::nef::model

#endif /* CnType_H_ */
