/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DddStatus.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

DddStatus::DddStatus() {}

void DddStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool DddStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool DddStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "DddStatus" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool DddStatus::operator==(const DddStatus& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool DddStatus::operator!=(const DddStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DddStatus& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, DddStatus& o) {
  from_json(j, o.m_value);
}

DddStatus_anyOf DddStatus::getValue() const {
  return m_value;
}

void DddStatus::setValue(DddStatus_anyOf value) {
  m_value = value;
}

DddStatus_anyOf::eDddStatus_anyOf DddStatus::getEnumValue() const {
  return m_value.getValue();
}

void DddStatus::setEnumValue(DddStatus_anyOf::eDddStatus_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
