/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "DlDataDeliveryStatus.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

DlDataDeliveryStatus::DlDataDeliveryStatus() {}

void DlDataDeliveryStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool DlDataDeliveryStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool DlDataDeliveryStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "DlDataDeliveryStatus" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool DlDataDeliveryStatus::operator==(const DlDataDeliveryStatus& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool DlDataDeliveryStatus::operator!=(const DlDataDeliveryStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const DlDataDeliveryStatus& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, DlDataDeliveryStatus& o) {
  from_json(j, o.m_value);
}

DlDataDeliveryStatus_anyOf DlDataDeliveryStatus::getValue() const {
  return m_value;
}

void DlDataDeliveryStatus::setValue(DlDataDeliveryStatus_anyOf value) {
  m_value = value;
}

DlDataDeliveryStatus_anyOf::eDlDataDeliveryStatus_anyOf
DlDataDeliveryStatus::getEnumValue() const {
  return m_value.getValue();
}

void DlDataDeliveryStatus::setEnumValue(
    DlDataDeliveryStatus_anyOf::eDlDataDeliveryStatus_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
