/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ExpectedAnalyticsType_anyOf.h
 *
 *
 */

#ifndef ExpectedAnalyticsType_anyOf_H_
#define ExpectedAnalyticsType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class ExpectedAnalyticsType_anyOf {
 public:
  ExpectedAnalyticsType_anyOf();
  virtual ~ExpectedAnalyticsType_anyOf() = default;

  enum class eExpectedAnalyticsType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    MOBILITY,
    COMMUN,
    MOBILITY_AND_COMMUN
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ExpectedAnalyticsType_anyOf& rhs) const;
  bool operator!=(const ExpectedAnalyticsType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// ExpectedAnalyticsType_anyOf members

  ExpectedAnalyticsType_anyOf::eExpectedAnalyticsType_anyOf getValue() const;
  void setValue(
      ExpectedAnalyticsType_anyOf::eExpectedAnalyticsType_anyOf value);

  friend void to_json(nlohmann::json& j, const ExpectedAnalyticsType_anyOf& o);
  friend void from_json(
      const nlohmann::json& j, ExpectedAnalyticsType_anyOf& o);

 protected:
  ExpectedAnalyticsType_anyOf::eExpectedAnalyticsType_anyOf m_value =
      ExpectedAnalyticsType_anyOf::eExpectedAnalyticsType_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::nef::model

#endif /* ExpectedAnalyticsType_anyOf_H_ */
