/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "GADShape.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

GADShape::GADShape() {}

void GADShape::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool GADShape::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool GADShape::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "GADShape" : pathPrefix;

  return success;
}

bool GADShape::operator==(const GADShape& rhs) const {
  return

      (getShape() == rhs.getShape())

          ;
}

bool GADShape::operator!=(const GADShape& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const GADShape& o) {
  j          = nlohmann::json();
  j["shape"] = o.m_Shape;
}

void from_json(const nlohmann::json& j, GADShape& o) {
  j.at("shape").get_to(o.m_Shape);
}

SupportedGADShapes GADShape::getShape() const {
  return m_Shape;
}
void GADShape::setShape(SupportedGADShapes const& value) {
  m_Shape = value;
}

}  // namespace oai::nef::model
