/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LcsQosClass.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

LcsQosClass::LcsQosClass() {}

void LcsQosClass::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool LcsQosClass::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool LcsQosClass::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "LcsQosClass" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool LcsQosClass::operator==(const LcsQosClass& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool LcsQosClass::operator!=(const LcsQosClass& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const LcsQosClass& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, LcsQosClass& o) {
  from_json(j, o.m_value);
}

LcsQosClass_anyOf LcsQosClass::getValue() const {
  return m_value;
}

void LcsQosClass::setValue(LcsQosClass_anyOf value) {
  m_value = value;
}

LcsQosClass_anyOf::eLcsQosClass_anyOf LcsQosClass::getEnumValue() const {
  return m_value.getValue();
}

void LcsQosClass::setEnumValue(LcsQosClass_anyOf::eLcsQosClass_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
