/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LocationType_anyOf.h
 *
 *
 */

#ifndef LocationType_anyOf_H_
#define LocationType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class LocationType_anyOf {
 public:
  LocationType_anyOf();
  virtual ~LocationType_anyOf() = default;

  enum class eLocationType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    CURRENT_LOCATION,
    LAST_KNOWN_LOCATION,
    CURRENT_OR_LAST_KNOWN_LOCATION,
    INITIAL_LOCATION
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const LocationType_anyOf& rhs) const;
  bool operator!=(const LocationType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// LocationType_anyOf members

  LocationType_anyOf::eLocationType_anyOf getValue() const;
  void setValue(LocationType_anyOf::eLocationType_anyOf value);

  friend void to_json(nlohmann::json& j, const LocationType_anyOf& o);
  friend void from_json(const nlohmann::json& j, LocationType_anyOf& o);

 protected:
  LocationType_anyOf::eLocationType_anyOf m_value =
      LocationType_anyOf::eLocationType_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::nef::model

#endif /* LocationType_anyOf_H_ */
