/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NefEvent_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

NefEvent_anyOf::NefEvent_anyOf() {}

void NefEvent_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool NefEvent_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NefEvent_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NefEvent_anyOf" : pathPrefix;

  if (m_value ==
      NefEvent_anyOf::eNefEvent_anyOf::INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool NefEvent_anyOf::operator==(const NefEvent_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool NefEvent_anyOf::operator!=(const NefEvent_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NefEvent_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case NefEvent_anyOf::eNefEvent_anyOf::INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case NefEvent_anyOf::eNefEvent_anyOf::SVC_EXPERIENCE:
      j = "SVC_EXPERIENCE";
      break;
    case NefEvent_anyOf::eNefEvent_anyOf::UE_MOBILITY:
      j = "UE_MOBILITY";
      break;
    case NefEvent_anyOf::eNefEvent_anyOf::UE_COMM:
      j = "UE_COMM";
      break;
    case NefEvent_anyOf::eNefEvent_anyOf::EXCEPTIONS:
      j = "EXCEPTIONS";
      break;
  }
}

void from_json(const nlohmann::json& j, NefEvent_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "SVC_EXPERIENCE") {
    o.setValue(NefEvent_anyOf::eNefEvent_anyOf::SVC_EXPERIENCE);
  } else if (s == "UE_MOBILITY") {
    o.setValue(NefEvent_anyOf::eNefEvent_anyOf::UE_MOBILITY);
  } else if (s == "UE_COMM") {
    o.setValue(NefEvent_anyOf::eNefEvent_anyOf::UE_COMM);
  } else if (s == "EXCEPTIONS") {
    o.setValue(NefEvent_anyOf::eNefEvent_anyOf::EXCEPTIONS);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " NefEvent_anyOf::eNefEvent_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

NefEvent_anyOf::eNefEvent_anyOf NefEvent_anyOf::getValue() const {
  return m_value;
}
void NefEvent_anyOf::setValue(NefEvent_anyOf::eNefEvent_anyOf value) {
  m_value = value;
}

}  // namespace oai::nef::model
