/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NetworkPerfType_anyOf.h
 *
 *
 */

#ifndef NetworkPerfType_anyOf_H_
#define NetworkPerfType_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class NetworkPerfType_anyOf {
 public:
  NetworkPerfType_anyOf();
  virtual ~NetworkPerfType_anyOf() = default;

  enum class eNetworkPerfType_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    GNB_ACTIVE_RATIO,
    GNB_COMPUTING_USAGE,
    GNB_MEMORY_USAGE,
    GNB_DISK_USAGE,
    NUM_OF_UE,
    SESS_SUCC_RATIO,
    HO_SUCC_RATIO
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NetworkPerfType_anyOf& rhs) const;
  bool operator!=(const NetworkPerfType_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// NetworkPerfType_anyOf members

  NetworkPerfType_anyOf::eNetworkPerfType_anyOf getValue() const;
  void setValue(NetworkPerfType_anyOf::eNetworkPerfType_anyOf value);

  friend void to_json(nlohmann::json& j, const NetworkPerfType_anyOf& o);
  friend void from_json(const nlohmann::json& j, NetworkPerfType_anyOf& o);

 protected:
  NetworkPerfType_anyOf::eNetworkPerfType_anyOf m_value =
      NetworkPerfType_anyOf::eNetworkPerfType_anyOf::
          INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::nef::model

#endif /* NetworkPerfType_anyOf_H_ */
