/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * NetworkPerfRequirement.h
 *
 *
 */

#ifndef NetworkPerfRequirement_H_
#define NetworkPerfRequirement_H_

#include <nlohmann/json.hpp>

#include "NetworkPerfType.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class NetworkPerfRequirement {
 public:
  NetworkPerfRequirement();
  virtual ~NetworkPerfRequirement() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const NetworkPerfRequirement& rhs) const;
  bool operator!=(const NetworkPerfRequirement& rhs) const;

  /////////////////////////////////////////////
  /// NetworkPerfRequirement members

  /// <summary>
  ///
  /// </summary>
  NetworkPerfType getNwPerfType() const;
  void setNwPerfType(NetworkPerfType const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getRelativeRatio() const;
  void setRelativeRatio(int32_t const value);
  bool relativeRatioIsSet() const;
  void unsetRelativeRatio();
  /// <summary>
  ///
  /// </summary>
  int32_t getAbsoluteNum() const;
  void setAbsoluteNum(int32_t const value);
  bool absoluteNumIsSet() const;
  void unsetAbsoluteNum();

  friend void to_json(nlohmann::json& j, const NetworkPerfRequirement& o);
  friend void from_json(const nlohmann::json& j, NetworkPerfRequirement& o);

 protected:
  NetworkPerfType m_NwPerfType;

  int32_t m_RelativeRatio;
  bool m_RelativeRatioIsSet;
  int32_t m_AbsoluteNum;
  bool m_AbsoluteNumIsSet;
};

}  // namespace oai::nef::model

#endif /* NetworkPerfRequirement_H_ */
