/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "NotificationMethod_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

NotificationMethod_anyOf::NotificationMethod_anyOf() {}

void NotificationMethod_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool NotificationMethod_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool NotificationMethod_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "NotificationMethod_anyOf" : pathPrefix;

  if (m_value == NotificationMethod_anyOf::eNotificationMethod_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool NotificationMethod_anyOf::operator==(
    const NotificationMethod_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool NotificationMethod_anyOf::operator!=(
    const NotificationMethod_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const NotificationMethod_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case NotificationMethod_anyOf::eNotificationMethod_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case NotificationMethod_anyOf::eNotificationMethod_anyOf::PERIODIC:
      j = "PERIODIC";
      break;
    case NotificationMethod_anyOf::eNotificationMethod_anyOf::ONE_TIME:
      j = "ONE_TIME";
      break;
    case NotificationMethod_anyOf::eNotificationMethod_anyOf::
        ON_EVENT_DETECTION:
      j = "ON_EVENT_DETECTION";
      break;
  }
}

void from_json(const nlohmann::json& j, NotificationMethod_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "PERIODIC") {
    o.setValue(NotificationMethod_anyOf::eNotificationMethod_anyOf::PERIODIC);
  } else if (s == "ONE_TIME") {
    o.setValue(NotificationMethod_anyOf::eNotificationMethod_anyOf::ONE_TIME);
  } else if (s == "ON_EVENT_DETECTION") {
    o.setValue(NotificationMethod_anyOf::eNotificationMethod_anyOf::
                   ON_EVENT_DETECTION);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " NotificationMethod_anyOf::eNotificationMethod_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

NotificationMethod_anyOf::eNotificationMethod_anyOf
NotificationMethod_anyOf::getValue() const {
  return m_value;
}
void NotificationMethod_anyOf::setValue(
    NotificationMethod_anyOf::eNotificationMethod_anyOf value) {
  m_value = value;
}

}  // namespace oai::nef::model
