/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PdnType_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

PdnType_anyOf::PdnType_anyOf() {}

void PdnType_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool PdnType_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PdnType_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PdnType_anyOf" : pathPrefix;

  if (m_value ==
      PdnType_anyOf::ePdnType_anyOf::INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool PdnType_anyOf::operator==(const PdnType_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool PdnType_anyOf::operator!=(const PdnType_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PdnType_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case PdnType_anyOf::ePdnType_anyOf::INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case PdnType_anyOf::ePdnType_anyOf::IPV4:
      j = "IPV4";
      break;
    case PdnType_anyOf::ePdnType_anyOf::IPV6:
      j = "IPV6";
      break;
    case PdnType_anyOf::ePdnType_anyOf::IPV4V6:
      j = "IPV4V6";
      break;
    case PdnType_anyOf::ePdnType_anyOf::NON_IP:
      j = "NON_IP";
      break;
    case PdnType_anyOf::ePdnType_anyOf::ETHERNET:
      j = "ETHERNET";
      break;
  }
}

void from_json(const nlohmann::json& j, PdnType_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "IPV4") {
    o.setValue(PdnType_anyOf::ePdnType_anyOf::IPV4);
  } else if (s == "IPV6") {
    o.setValue(PdnType_anyOf::ePdnType_anyOf::IPV6);
  } else if (s == "IPV4V6") {
    o.setValue(PdnType_anyOf::ePdnType_anyOf::IPV4V6);
  } else if (s == "NON_IP") {
    o.setValue(PdnType_anyOf::ePdnType_anyOf::NON_IP);
  } else if (s == "ETHERNET") {
    o.setValue(PdnType_anyOf::ePdnType_anyOf::ETHERNET);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " PdnType_anyOf::ePdnType_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

PdnType_anyOf::ePdnType_anyOf PdnType_anyOf::getValue() const {
  return m_value;
}
void PdnType_anyOf::setValue(PdnType_anyOf::ePdnType_anyOf value) {
  m_value = value;
}

}  // namespace oai::nef::model
