/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Point.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

Point::Point() {}

void Point::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool Point::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Point::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "Point" : pathPrefix;

  return success;
}

bool Point::operator==(const Point& rhs) const {
  return

      (getShape() == rhs.getShape()) &&

      (getPoint() == rhs.getPoint())

          ;
}

bool Point::operator!=(const Point& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Point& o) {
  j          = nlohmann::json();
  j["shape"] = o.m_Shape;
  j["point"] = o.m_Point;
}

void from_json(const nlohmann::json& j, Point& o) {
  j.at("shape").get_to(o.m_Shape);
  j.at("point").get_to(o.m_Point);
}

SupportedGADShapes Point::getShape() const {
  return m_Shape;
}
void Point::setShape(SupportedGADShapes const& value) {
  m_Shape = value;
}
GeographicalCoordinates Point::getPoint() const {
  return m_Point;
}
void Point::setPoint(GeographicalCoordinates const& value) {
  m_Point = value;
}

}  // namespace oai::nef::model
