/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Point_allOf.h
 *
 *
 */

#ifndef Point_allOf_H_
#define Point_allOf_H_

#include <nlohmann/json.hpp>

#include "GeographicalCoordinates.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class Point_allOf {
 public:
  Point_allOf();
  virtual ~Point_allOf() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const Point_allOf& rhs) const;
  bool operator!=(const Point_allOf& rhs) const;

  /////////////////////////////////////////////
  /// Point_allOf members

  /// <summary>
  ///
  /// </summary>
  GeographicalCoordinates getPoint() const;
  void setPoint(GeographicalCoordinates const& value);

  friend void to_json(nlohmann::json& j, const Point_allOf& o);
  friend void from_json(const nlohmann::json& j, Point_allOf& o);

 protected:
  GeographicalCoordinates m_Point;
};

}  // namespace oai::nef::model

#endif /* Point_allOf_H_ */
