/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PositioningMethod.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

PositioningMethod::PositioningMethod() {}

void PositioningMethod::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool PositioningMethod::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PositioningMethod::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PositioningMethod" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool PositioningMethod::operator==(const PositioningMethod& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool PositioningMethod::operator!=(const PositioningMethod& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PositioningMethod& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, PositioningMethod& o) {
  from_json(j, o.m_value);
}

PositioningMethod_anyOf PositioningMethod::getValue() const {
  return m_value;
}

void PositioningMethod::setValue(PositioningMethod_anyOf value) {
  m_value = value;
}

PositioningMethod_anyOf::ePositioningMethod_anyOf
PositioningMethod::getEnumValue() const {
  return m_value.getValue();
}

void PositioningMethod::setEnumValue(
    PositioningMethod_anyOf::ePositioningMethod_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
