/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ReachabilityType.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

ReachabilityType::ReachabilityType() {}

void ReachabilityType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool ReachabilityType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ReachabilityType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ReachabilityType" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool ReachabilityType::operator==(const ReachabilityType& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool ReachabilityType::operator!=(const ReachabilityType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ReachabilityType& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, ReachabilityType& o) {
  from_json(j, o.m_value);
}

ReachabilityType_anyOf ReachabilityType::getValue() const {
  return m_value;
}

void ReachabilityType::setValue(ReachabilityType_anyOf value) {
  m_value = value;
}

ReachabilityType_anyOf::eReachabilityType_anyOf ReachabilityType::getEnumValue()
    const {
  return m_value.getValue();
}

void ReachabilityType::setEnumValue(
    ReachabilityType_anyOf::eReachabilityType_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
