/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ReleaseCause.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

ReleaseCause::ReleaseCause() {}

void ReleaseCause::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool ReleaseCause::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ReleaseCause::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ReleaseCause" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool ReleaseCause::operator==(const ReleaseCause& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool ReleaseCause::operator!=(const ReleaseCause& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ReleaseCause& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, ReleaseCause& o) {
  from_json(j, o.m_value);
}

ReleaseCause_anyOf ReleaseCause::getValue() const {
  return m_value;
}

void ReleaseCause::setValue(ReleaseCause_anyOf value) {
  m_value = value;
}

ReleaseCause_anyOf::eReleaseCause_anyOf ReleaseCause::getEnumValue() const {
  return m_value.getValue();
}

void ReleaseCause::setEnumValue(ReleaseCause_anyOf::eReleaseCause_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
