/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ResponseTime_anyOf.h"

#include <sstream>
#include <stdexcept>

#include "Helpers.h"

namespace oai::nef::model {

ResponseTime_anyOf::ResponseTime_anyOf() {}

void ResponseTime_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool ResponseTime_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ResponseTime_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ResponseTime_anyOf" : pathPrefix;

  if (m_value == ResponseTime_anyOf::eResponseTime_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool ResponseTime_anyOf::operator==(const ResponseTime_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool ResponseTime_anyOf::operator!=(const ResponseTime_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ResponseTime_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case ResponseTime_anyOf::eResponseTime_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case ResponseTime_anyOf::eResponseTime_anyOf::LOW_DELAY:
      j = "LOW_DELAY";
      break;
    case ResponseTime_anyOf::eResponseTime_anyOf::DELAY_TOLERANT:
      j = "DELAY_TOLERANT";
      break;
    case ResponseTime_anyOf::eResponseTime_anyOf::NO_DELAY:
      j = "NO_DELAY";
      break;
  }
}

void from_json(const nlohmann::json& j, ResponseTime_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "LOW_DELAY") {
    o.setValue(ResponseTime_anyOf::eResponseTime_anyOf::LOW_DELAY);
  } else if (s == "DELAY_TOLERANT") {
    o.setValue(ResponseTime_anyOf::eResponseTime_anyOf::DELAY_TOLERANT);
  } else if (s == "NO_DELAY") {
    o.setValue(ResponseTime_anyOf::eResponseTime_anyOf::NO_DELAY);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " ResponseTime_anyOf::eResponseTime_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

ResponseTime_anyOf::eResponseTime_anyOf ResponseTime_anyOf::getValue() const {
  return m_value;
}
void ResponseTime_anyOf::setValue(
    ResponseTime_anyOf::eResponseTime_anyOf value) {
  m_value = value;
}

}  // namespace oai::nef::model
