/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ResponseTime.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

ResponseTime::ResponseTime() {}

void ResponseTime::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool ResponseTime::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ResponseTime::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ResponseTime" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool ResponseTime::operator==(const ResponseTime& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool ResponseTime::operator!=(const ResponseTime& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ResponseTime& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, ResponseTime& o) {
  from_json(j, o.m_value);
}

ResponseTime_anyOf ResponseTime::getValue() const {
  return m_value;
}

void ResponseTime::setValue(ResponseTime_anyOf value) {
  m_value = value;
}

ResponseTime_anyOf::eResponseTime_anyOf ResponseTime::getEnumValue() const {
  return m_value.getValue();
}

void ResponseTime::setEnumValue(ResponseTime_anyOf::eResponseTime_anyOf value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
