/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ResultReason_anyOf.h
 *
 *
 */

#ifndef ResultReason_anyOf_H_
#define ResultReason_anyOf_H_

#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class ResultReason_anyOf {
 public:
  ResultReason_anyOf();
  virtual ~ResultReason_anyOf() = default;

  enum class eResultReason_anyOf {
    // To have a valid default value.
    // Avoiding name clashes with user defined
    // enum values
    INVALID_VALUE_OPENAPI_GENERATED = 0,
    ROAMING_NOT_ALLOWED,
    OTHER_REASON
  };

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const ResultReason_anyOf& rhs) const;
  bool operator!=(const ResultReason_anyOf& rhs) const;

  /////////////////////////////////////////////
  /// ResultReason_anyOf members

  ResultReason_anyOf::eResultReason_anyOf getValue() const;
  void setValue(ResultReason_anyOf::eResultReason_anyOf value);

  friend void to_json(nlohmann::json& j, const ResultReason_anyOf& o);
  friend void from_json(const nlohmann::json& j, ResultReason_anyOf& o);

 protected:
  ResultReason_anyOf::eResultReason_anyOf m_value =
      ResultReason_anyOf::eResultReason_anyOf::INVALID_VALUE_OPENAPI_GENERATED;
};

}  // namespace oai::nef::model

#endif /* ResultReason_anyOf_H_ */
