/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SACEventStatus.h
 *
 * Contains the network slice status information in terms of the current number
 * of UEs registered with a network slice, the current number of PDU Sessions
 * established on a network slice or both.
 */

#ifndef SACEventStatus_H_
#define SACEventStatus_H_

#include <nlohmann/json.hpp>

#include "SACInfo.h"

namespace oai::nef::model {

/// <summary>
/// Contains the network slice status information in terms of the current number
/// of UEs registered with a network slice, the current number of PDU Sessions
/// established on a network slice or both.
/// </summary>
class SACEventStatus {
 public:
  SACEventStatus();
  virtual ~SACEventStatus() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SACEventStatus& rhs) const;
  bool operator!=(const SACEventStatus& rhs) const;

  /////////////////////////////////////////////
  /// SACEventStatus members

  /// <summary>
  ///
  /// </summary>
  SACInfo getReachedNumUes() const;
  void setReachedNumUes(SACInfo const& value);
  bool reachedNumUesIsSet() const;
  void unsetReachedNumUes();
  /// <summary>
  ///
  /// </summary>
  SACInfo getReachedNumPduSess() const;
  void setReachedNumPduSess(SACInfo const& value);
  bool reachedNumPduSessIsSet() const;
  void unsetReachedNumPduSess();

  friend void to_json(nlohmann::json& j, const SACEventStatus& o);
  friend void from_json(const nlohmann::json& j, SACEventStatus& o);

 protected:
  SACInfo m_ReachedNumUes;
  bool m_ReachedNumUesIsSet;
  SACInfo m_ReachedNumPduSess;
  bool m_ReachedNumPduSessIsSet;
};

}  // namespace oai::nef::model

#endif /* SACEventStatus_H_ */
