/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmallDataRateControlTimeUnit.h"

#include <sstream>

#include "Helpers.h"

namespace oai::nef::model {

SmallDataRateControlTimeUnit::SmallDataRateControlTimeUnit() {}

void SmallDataRateControlTimeUnit::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::nef::helpers::ValidationException(msg.str());
  }
}

bool SmallDataRateControlTimeUnit::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmallDataRateControlTimeUnit::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmallDataRateControlTimeUnit" : pathPrefix;

  if (!m_value.validate(msg)) {
    success = false;
  }
  return success;
}

bool SmallDataRateControlTimeUnit::operator==(
    const SmallDataRateControlTimeUnit& rhs) const {
  return

      getValue() == rhs.getValue();
}

bool SmallDataRateControlTimeUnit::operator!=(
    const SmallDataRateControlTimeUnit& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmallDataRateControlTimeUnit& o) {
  j = nlohmann::json();
  to_json(j, o.m_value);
}

void from_json(const nlohmann::json& j, SmallDataRateControlTimeUnit& o) {
  from_json(j, o.m_value);
}

SmallDataRateControlTimeUnit_anyOf SmallDataRateControlTimeUnit::getValue()
    const {
  return m_value;
}

void SmallDataRateControlTimeUnit::setValue(
    SmallDataRateControlTimeUnit_anyOf value) {
  m_value = value;
}

SmallDataRateControlTimeUnit_anyOf::eSmallDataRateControlTimeUnit_anyOf
SmallDataRateControlTimeUnit::getEnumValue() const {
  return m_value.getValue();
}

void SmallDataRateControlTimeUnit::setEnumValue(
    SmallDataRateControlTimeUnit_anyOf::eSmallDataRateControlTimeUnit_anyOf
        value) {
  m_value.setValue(value);
}

}  // namespace oai::nef::model
