/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmContextUpdateData.h
 *
 *
 */

#ifndef SmContextUpdateData_H_
#define SmContextUpdateData_H_

#include <nlohmann/json.hpp>
#include <string>

#include "SmContextConfiguration.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class SmContextUpdateData {
 public:
  SmContextUpdateData();
  virtual ~SmContextUpdateData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmContextUpdateData& rhs) const;
  bool operator!=(const SmContextUpdateData& rhs) const;

  /////////////////////////////////////////////
  /// SmContextUpdateData members

  /// <summary>
  ///
  /// </summary>
  std::string getDlNiddEndPoint() const;
  void setDlNiddEndPoint(std::string const& value);
  bool dlNiddEndPointIsSet() const;
  void unsetDlNiddEndPoint();
  /// <summary>
  ///
  /// </summary>
  std::string getNotificationUri() const;
  void setNotificationUri(std::string const& value);
  bool notificationUriIsSet() const;
  void unsetNotificationUri();
  /// <summary>
  ///
  /// </summary>
  SmContextConfiguration getSmContextConfig() const;
  void setSmContextConfig(SmContextConfiguration const& value);
  bool smContextConfigIsSet() const;
  void unsetSmContextConfig();

  friend void to_json(nlohmann::json& j, const SmContextUpdateData& o);
  friend void from_json(const nlohmann::json& j, SmContextUpdateData& o);

 protected:
  std::string m_DlNiddEndPoint;
  bool m_DlNiddEndPointIsSet;
  std::string m_NotificationUri;
  bool m_NotificationUriIsSet;
  SmContextConfiguration m_SmContextConfig;
  bool m_SmContextConfigIsSet;
};

}  // namespace oai::nef::model

#endif /* SmContextUpdateData_H_ */
