/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SmContextCreatedData.h
 *
 *
 */

#ifndef SmContextCreatedData_H_
#define SmContextCreatedData_H_

#include <nlohmann/json.hpp>
#include <string>

#include "Snssai.h"

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class SmContextCreatedData {
 public:
  SmContextCreatedData();
  virtual ~SmContextCreatedData() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const SmContextCreatedData& rhs) const;
  bool operator!=(const SmContextCreatedData& rhs) const;

  /////////////////////////////////////////////
  /// SmContextCreatedData members

  /// <summary>
  ///
  /// </summary>
  std::string getSupi() const;
  void setSupi(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getPduSessionId() const;
  void setPduSessionId(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  std::string getDnn() const;
  void setDnn(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  Snssai getSnssai() const;
  void setSnssai(Snssai const& value);
  /// <summary>
  /// This IE shall contain the NEF ID of the target NEF.
  /// </summary>
  std::string getNefId() const;
  void setNefId(std::string const& value);
  /// <summary>
  /// When present, this IE shall indicate the NEF capability to support RDS.
  /// The value of this IE shall be set as following   - true  NEF supports RDS
  /// - false (default)  NEF does not support RDS
  /// </summary>
  bool isRdsSupport() const;
  void setRdsSupport(bool const value);
  bool rdsSupportIsSet() const;
  void unsetRdsSupport();
  /// <summary>
  /// When present, this IE shall indicate whether Extended Buffering applies or
  /// not. The value of this IE shall be set as following   - true  Extended
  /// Buffering applies   - false (default)  Extended Buffering does not apply
  /// </summary>
  bool isExtBufSupport() const;
  void setExtBufSupport(bool const value);
  bool extBufSupportIsSet() const;
  void unsetExtBufSupport();
  /// <summary>
  ///
  /// </summary>
  std::string getSupportedFeatures() const;
  void setSupportedFeatures(std::string const& value);
  bool supportedFeaturesIsSet() const;
  void unsetSupportedFeatures();
  /// <summary>
  ///
  /// </summary>
  int32_t getMaxPacketSize() const;
  void setMaxPacketSize(int32_t const value);
  bool maxPacketSizeIsSet() const;
  void unsetMaxPacketSize();

  friend void to_json(nlohmann::json& j, const SmContextCreatedData& o);
  friend void from_json(const nlohmann::json& j, SmContextCreatedData& o);

 protected:
  std::string m_Supi;

  int32_t m_PduSessionId;

  std::string m_Dnn;

  Snssai m_Snssai;

  std::string m_NefId;

  bool m_RdsSupport;
  bool m_RdsSupportIsSet;
  bool m_ExtBufSupport;
  bool m_ExtBufSupportIsSet;
  std::string m_SupportedFeatures;
  bool m_SupportedFeaturesIsSet;
  int32_t m_MaxPacketSize;
  bool m_MaxPacketSizeIsSet;
};

}  // namespace oai::nef::model

#endif /* SmContextCreatedData_H_ */
