/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2020, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1.alpha-5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ReportingFrequency_anyOf.h"
#include "Helpers.h"
#include <stdexcept>
#include <sstream>

namespace oai {
namespace pcf {
namespace model {

ReportingFrequency_anyOf::ReportingFrequency_anyOf() {}

void ReportingFrequency_anyOf::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    //        throw
    //        org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool ReportingFrequency_anyOf::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ReportingFrequency_anyOf::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ReportingFrequency_anyOf" : pathPrefix;

  if (m_value == ReportingFrequency_anyOf::eReportingFrequency_anyOf::
                     INVALID_VALUE_OPENAPI_GENERATED) {
    success = false;
    msg << _pathPrefix << ": has no value;";
  }

  return success;
}

bool ReportingFrequency_anyOf::operator==(
    const ReportingFrequency_anyOf& rhs) const {
  return getValue() == rhs.getValue()

      ;
}

bool ReportingFrequency_anyOf::operator!=(
    const ReportingFrequency_anyOf& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ReportingFrequency_anyOf& o) {
  j = nlohmann::json();

  switch (o.getValue()) {
    case ReportingFrequency_anyOf::eReportingFrequency_anyOf::
        INVALID_VALUE_OPENAPI_GENERATED:
      j = "INVALID_VALUE_OPENAPI_GENERATED";
      break;
    case ReportingFrequency_anyOf::eReportingFrequency_anyOf::EVENT_TRIGGERED:
      j = "EVENT_TRIGGERED";
      break;
    case ReportingFrequency_anyOf::eReportingFrequency_anyOf::PERIODIC:
      j = "PERIODIC";
      break;
    case ReportingFrequency_anyOf::eReportingFrequency_anyOf::SESSION_RELEASE:
      j = "SESSION_RELEASE";
      break;
  }
}

void from_json(const nlohmann::json& j, ReportingFrequency_anyOf& o) {
  auto s = j.get<std::string>();
  if (s == "EVENT_TRIGGERED") {
    o.setValue(
        ReportingFrequency_anyOf::eReportingFrequency_anyOf::EVENT_TRIGGERED);
  } else if (s == "PERIODIC") {
    o.setValue(ReportingFrequency_anyOf::eReportingFrequency_anyOf::PERIODIC);
  } else if (s == "SESSION_RELEASE") {
    o.setValue(
        ReportingFrequency_anyOf::eReportingFrequency_anyOf::SESSION_RELEASE);
  } else {
    std::stringstream ss;
    ss << "Unexpected value " << s << " in json"
       << " cannot be converted to enum of type"
       << " ReportingFrequency_anyOf::eReportingFrequency_anyOf";
    throw std::invalid_argument(ss.str());
  }
}

ReportingFrequency_anyOf::eReportingFrequency_anyOf
ReportingFrequency_anyOf::getValue() const {
  return m_value;
}
void ReportingFrequency_anyOf::setValue(
    ReportingFrequency_anyOf::eReportingFrequency_anyOf value) {
  m_value = value;
}

}  // namespace model
}  // namespace pcf
}  // namespace oai
