/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2020, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1.alpha-5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * TsnPortIdentifier.h
 *
 *
 */

#ifndef TsnPortIdentifier_H_
#define TsnPortIdentifier_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai {
namespace pcf {
namespace model {

/// <summary>
///
/// </summary>
class TsnPortIdentifier {
 public:
  TsnPortIdentifier();
  virtual ~TsnPortIdentifier() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  /// <summary>
  /// Helper overload for validate. Used when one model stores another model and
  /// calls it's validate. Not meant to be called outside that case.
  /// </summary>
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

  bool operator==(const TsnPortIdentifier& rhs) const;
  bool operator!=(const TsnPortIdentifier& rhs) const;

  /////////////////////////////////////////////
  /// TsnPortIdentifier members

  /// <summary>
  ///
  /// </summary>
  std::string getPortMac() const;
  void setPortMac(std::string const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getPortNumber() const;
  void setPortNumber(int32_t const value);
  bool portNumberIsSet() const;
  void unsetPortNumber();

  friend void to_json(nlohmann::json& j, const TsnPortIdentifier& o);
  friend void from_json(const nlohmann::json& j, TsnPortIdentifier& o);

 protected:
  std::string m_PortMac;

  int32_t m_PortNumber;
  bool m_PortNumberIsSet;
};

}  // namespace model
}  // namespace pcf
}  // namespace oai
#endif /* TsnPortIdentifier_H_ */
