/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AFLevelUELocationUpdateNotificationOperationApi.h
 *
 *
 */

#ifndef AFLevelUELocationUpdateNotificationOperationApi_H_
#define AFLevelUELocationUpdateNotificationOperationApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <string>
#include <utility>

#include "LocUpdateData.h"
#include "LocUpdateDataReply.h"
#include "ProblemDetails.h"

namespace oai::nef::api {

class AFLevelUELocationUpdateNotificationOperationApi {
 public:
  explicit AFLevelUELocationUpdateNotificationOperationApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~AFLevelUELocationUpdateNotificationOperationApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void root_post_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void af_level_ue_location_update_notification_operation_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// UE location information update notification
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="locUpdateData"></param>
  virtual void root_post(
      const oai::nef::model::LocUpdateData& locUpdateData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::nef::api

#endif /* AFLevelUELocationUpdateNotificationOperationApi_H_ */
