/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SMContextsCollectionCollectionApi.h
 *
 *
 */

#ifndef SMContextsCollectionCollectionApi_H_
#define SMContextsCollectionCollectionApi_H_

#include <pistache/http.h>
#include <pistache/http_headers.h>
#include <pistache/router.h>

#include <optional>
#include <string>
#include <utility>

#include "ProblemDetails.h"
#include "SmContextCreateData.h"
#include "SmContextCreatedData.h"

namespace oai::nef::api {

class SMContextsCollectionCollectionApi {
 public:
  explicit SMContextsCollectionCollectionApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~SMContextsCollectionCollectionApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void create_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void sm_contexts_collection_collection_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Create SM Context
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="smContextCreateData"></param>
  virtual void create(
      const oai::nef::model::SmContextCreateData& smContextCreateData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace oai::nef::api

#endif /* SMContextsCollectionCollectionApi_H_ */
