apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnb-du.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: f1c
      port: 38472
      targetPort: 38472
      protocol: SCTP
    - name: f1u
      port: 2152
      targetPort: 2152
      protocol: UDP
  selector:
    {{- include "oai-gnb-du.selectorLabels" . | nindent 4 }}
