version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai-nssf:
        container_name: "oai-nssf"
        image: oaisoftwarealliance/oai-nssf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - NSSF_NAME=oai-nssf
            - NSSF_FQDN=nssf.oai-5gcn.eur
            - SBI_IF_NAME=eth0
            - SBI_PORT_HTTP2=8080
            - SBI_API_VERSION=v1
            # NSSF is not registered to NRF
            - NSSF_SLICE_CONFIG=/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        volumes: 
            - ./nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai_udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - UDR_NAME=OAI_UDR
            - UDR_INTERFACE_NAME_FOR_NUDR=eth0
            - MYSQL_IPV4_ADDRESS=192.168.70.131
            - MYSQL_USER=test
            - MYSQL_PASS=test
            - MYSQL_DB=oai_db
            - WAIT_MYSQL=120
            # UDR is not registered to NRF
            # changes for HTTP2
            - USE_HTTP2=yes
            - UDR_INTERFACE_HTTP2_PORT_FOR_NUDR=8080
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.70.133
    oai_udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - USE_FQDN_DNS=yes
            # UDM is not registered to NRF
            - UDR_IP_ADDRESS=192.168.70.133
            - UDR_VERSION_NB=v1
            - UDR_FQDN=oai_udr
            # changes for HTTP2
            - USE_HTTP2=yes
            - SBI_HTTP2_PORT=8080
            - UDR_PORT=8080
        depends_on:
            - oai_udr
        networks:
            public_net:
                ipv4_address: 192.168.70.134
    oai_ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - USE_FQDN_DNS=yes
            # AUSF is not registered to NRF
            - UDM_IP_ADDRESS=192.168.70.134
            - UDM_VERSION_NB=v1
            - UDM_FQDN=oai_udm
            # changes for HTTP2
            - USE_HTTP2=yes
            - UDM_PORT=8080
        depends_on:
            - oai_udm
        networks:
            public_net:
                ipv4_address: 192.168.70.135
    oai_nrf_slice12:
        container_name: "oai-nrf-slice12"
        image: oaisoftwarealliance/oai-nrf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            # The default HTTP2 port is 8080 for all network functions
            # It is shown here as example.
            # If you wish to change, you have to specify it for each NF
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    oai_nrf_slice3:
        container_name: "oai-nrf-slice3"
        image: oaisoftwarealliance/oai-nrf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            # The default HTTP2 port is 8080 for all network functions
            # It is shown here as example.
            # If you wish to change, you have to specify it for each NF
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
        networks:
            public_net:
                ipv4_address: 192.168.70.137
    oai_amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        environment:
            - TZ=Europe/Paris
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            # Slice 0 (128, 128)
            - SST_0=128
            - SD_0=128
            # Slice 1 (1, 0xFFFFFF)
            - SST_1=1
            # Slice 2 (130, 130)
            - SST_2=130
            - SD_2=130
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            # First SMF instance
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai_smf_slice1
            - SMF_HTTP_VERSION_0=v1
            - SELECTED_0=true
            # Second SMF instance
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=oai_smf_slice2
            - SMF_HTTP_VERSION_1=v1
            - SELECTED_1=false
            # Feature list
            - EXTERNAL_NRF=no
            - NRF_SELECTION=yes
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - EXTERNAL_AUSF=yes
            - EXTERNAL_NSSF=yes
            - INT_ALGO_LIST=["NIA1" , "NIA2"]
            - CIPH_ALGO_LIST=["NEA1" , "NEA2"]
            # Other NF
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_FQDN=oai_nrf_slice12
            - AUSF_IPV4_ADDRESS=192.168.70.135
            - AUSF_FQDN=oai_ausf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_FQDN=oai_udm
            - NSSF_IPV4_ADDRESS=192.168.70.132
            - NSSF_FQDN=oai-nssf
            # changes for HTTP2
            - USE_HTTP2=yes
            - NRF_PORT=8080
            - AUSF_PORT=8080
            - UDM_PORT=8080
            - NSSF_PORT=8080
        depends_on:
            - mysql
            - oai_nrf_slice12
            - vpp_upf_slice3
            - oai_ausf
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai_smf_slice1:
        container_name: "oai-smf-slice1"
        image: oaisoftwarealliance/oai-smf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        environment:
            - TZ=Europe/Paris
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_FQDN=oai_udm
            - UPF_IPV4_ADDRESS=127.0.0.1
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_FQDN=oai_nrf_slice12
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - DISCOVER_PCF=no
            - USE_LOCAL_SUBSCRIPTION_INFO=yes
            - USE_LOCAL_PCC_RULES=yes
            - USE_FQDN_DNS=yes
            # One single slice is defined.
            - DNN_NI0=default
            - TYPE0=IPv4
            - DNN_RANGE0=12.2.1.2 - 12.2.1.128
            - NSSAI_SST0=128
            - NSSAI_SD0=128
            - SESSION_AMBR_UL0=50Mbps
            - SESSION_AMBR_DL0=100Mbps
            # changes for HTTP2
            - HTTP_VERSION=2
            - AMF_PORT=8080
            - UDM_PORT=8080
            - NRF_PORT=8080
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.139
    oai_smf_slice2:
        container_name: "oai-smf-slice2"
        image: oaisoftwarealliance/oai-smf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        environment:
            - TZ=Europe/Paris
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=0.0.0.0
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_FQDN=oai_nrf_slice12
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - DISCOVER_PCF=no
            - USE_LOCAL_SUBSCRIPTION_INFO=yes
            - USE_LOCAL_PCC_RULES=yes
            - USE_FQDN_DNS=yes
            # One single slice is defined.
            - DNN_NI0=oai
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.129 - 12.1.1.224
            - NSSAI_SST0=1
            - SESSION_AMBR_UL0=200Mbps
            - SESSION_AMBR_DL0=400Mbps
            # changes for HTTP2
            - HTTP_VERSION=2
            - AMF_PORT=8080
            - UDM_PORT=8080
            - NRF_PORT=8080
        depends_on:
            - oai_amf
            - oai_nrf_slice12
        networks:
            public_net:
                ipv4_address: 192.168.70.140
    oai_smf_slice3:
        container_name: "oai-smf-slice3"
        image: oaisoftwarealliance/oai-smf:v1.5.1
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        environment:
            - TZ=Europe/Paris
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - DEFAULT_DNS_IPV4_ADDRESS=172.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=192.168.70.138
            - AMF_FQDN=oai_amf
            - UDM_IPV4_ADDRESS=192.168.70.134
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=0.0.0.0
            - UPF_FQDN_0=localhost
            - NRF_IPV4_ADDRESS=192.168.70.137
            - NRF_FQDN=oai_nrf_slice3
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - DISCOVER_PCF=no
            - USE_LOCAL_SUBSCRIPTION_INFO=yes
            - USE_LOCAL_PCC_RULES=yes
            - USE_FQDN_DNS=yes
            # One single slice is defined.
            - DNN_NI0=oai.ipv4
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.2 - 12.1.1.128
            - NSSAI_SST0=130
            - NSSAI_SD0=130
            - SESSION_AMBR_UL0=100Mbps
            - SESSION_AMBR_DL0=200Mbps
            # changes for HTTP2
            - HTTP_VERSION=2
            - AMF_PORT=8080
            - UDM_PORT=8080
            - NRF_PORT=8080
        depends_on:
            - oai_amf
            - oai_nrf_slice3
        extra_hosts:
            - "vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.70.201"
        networks:
            public_net:
                ipv4_address: 192.168.70.141
    oai_spgwu_slice1:
        container_name: "oai-spgwu-slice1"
        image: oaisoftwarealliance/oai-spgwu-tiny:v1.5.1
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.2.1.0/24
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai_spgwu_slice1
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            # Mandatory to set the NRF PORT to 8080 (it is set to default to 80 otherwise)
            - HTTP_VERSION=2
            - NRF_PORT=8080
            # One single slice / DNN is defined
            - NSSAI_SST_0=128
            - NSSAI_SD_0=128
            - DNN_0=default
        depends_on:
            - oai_nrf_slice12
            - oai_smf_slice1
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.142
    oai_spgwu_slice2:
        container_name: "oai-spgwu-slice2"
        image: oaisoftwarealliance/oai-spgwu-tiny:v1.5.1
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        environment:
            - TZ=Europe/Paris
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=oai_spgwu_slice2
            - NRF_IPV4_ADDRESS=192.168.70.136
            - NRF_API_VERSION=v1
            - NRF_FQDN=oai_nrf_slice12
            # Mandatory to set the NRF PORT to 8080 (it is set to default to 80 otherwise)
            - HTTP_VERSION=2
            - NRF_PORT=8080
            # One single slice / DNN is defined
            - NSSAI_SST_0=1
            - DNN_0=oai
        depends_on:
            - oai_nrf_slice12
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.143
    vpp_upf_slice3:
        container_name: "vpp-upf-slice3"
        image: oaisoftwarealliance/oai-upf-vpp:v1.5.1
        privileged: true
        environment:
            - IF_1_IP=192.168.70.201
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.72.201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.oai.org
            - IF_3_IP=192.168.73.201
            - IF_3_TYPE=N6
            - IF_3_IP_REMOTE=192.168.73.145 # EXT-DN IP Address
            - IF_3_NWI=internet.oai.org
            - NAME=VPP-UPF
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/
            - SNSSAI_SD=130
            - SNSSAI_SST=130
            - DNN=oai.ipv4
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.70.137
            - NRF_PORT=8080
            - HTTP_VERSION=2
        depends_on:
            - oai_nrf_slice3
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: 192.168.70.144
            public_net_access:
                ipv4_address: 192.168.72.144
            public_net_core:
                ipv4_address: 192.168.73.144
    oai_ext_dn:
        image: oaisoftwarealliance/trf-gen-cn5g:latest
        privileged: true
        init: true
        container_name: oai-ext-dn
        entrypoint: /bin/bash -c \
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.2.1.2/32 via 192.168.70.142 dev eth0;"\
              "ip route add 12.1.1.129/32 via 192.168.70.143 dev eth0;"\
              "ip route add 12.1.1.2/32 via 192.168.73.201 dev eth1; ip route; sleep infinity"
        command: ["/bin/bash", "-c", "trap : SIGTERM SIGINT; sleep infinity & wait"]
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 10
        networks:
            public_net:
                ipv4_address: 192.168.70.145
            public_net_core:
                ipv4_address: 192.168.73.145
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core"
