/**
 * Npcf_SMPolicyControl API
 * Session Management Policy Control Service © 2020, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.1.alpha-5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * SMPoliciesCollectionApi.h
 *
 *
 */

#ifndef SMPoliciesCollectionApi_H_
#define SMPoliciesCollectionApi_H_

#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/http_headers.h>

#include <optional>
#include <utility>

#include "ProblemDetails.h"
#include "SmPolicyContextData.h"
#include "SmPolicyDecision.h"
#include <string>
#include "Helpers.h"

namespace oai {
namespace pcf {
namespace api {

using namespace oai::model::common::helpers;
using namespace oai::pcf::model;

class SMPoliciesCollectionApi {
 public:
  explicit SMPoliciesCollectionApi(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  virtual ~SMPoliciesCollectionApi() = default;
  void init();

  static const std::string base;

 private:
  void setupRoutes();

  void create_sm_policy_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);
  void sm_policies_collection_api_default_handler(
      const Pistache::Rest::Request& request,
      Pistache::Http::ResponseWriter response);

  const std::shared_ptr<Pistache::Rest::Router> router;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during Parameter parsing
  /// and validation. May be overridden to return custom error formats. This is
  /// called inside a catch block. Important: When overriding, do not call
  /// `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleParsingException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Helper function to handle unexpected Exceptions during processing of the
  /// request in handler functions. May be overridden to return custom error
  /// formats. This is called inside a catch block. Important: When overriding,
  /// do not call `throw ex;`, but instead use `throw;`.
  /// </summary>
  virtual std::pair<Pistache::Http::Code, std::string> handleOperationException(
      const std::exception& ex) const noexcept;

  /// <summary>
  /// Create a new Individual SM Policy
  /// </summary>
  /// <remarks>
  ///
  /// </remarks>
  /// <param name="smPolicyContextData"></param>
  virtual void create_sm_policy(
      const oai::pcf::model::SmPolicyContextData& smPolicyContextData,
      Pistache::Http::ResponseWriter& response) = 0;
};

}  // namespace api
}  // namespace pcf
}  // namespace oai

#endif /* SMPoliciesCollectionApi_H_ */
