/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AFLevelUELocationUpdateNotificationOperationApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

AFLevelUELocationUpdateNotificationOperationApiImpl::
    AFLevelUELocationUpdateNotificationOperationApiImpl(
        const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : AFLevelUELocationUpdateNotificationOperationApi(rtr) {}

void AFLevelUELocationUpdateNotificationOperationApiImpl::root_post(
    const LocUpdateData& locUpdateData,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
