/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AnalyticsExposureAPIFetchAnalyticsInformationApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

AnalyticsExposureAPIFetchAnalyticsInformationApiImpl::
    AnalyticsExposureAPIFetchAnalyticsInformationApiImpl(
        const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : AnalyticsExposureAPIFetchAnalyticsInformationApi(rtr) {}

void AnalyticsExposureAPIFetchAnalyticsInformationApiImpl::af_id_fetch_post(
    const std::string& afId, const AnalyticsRequest& analyticsRequest,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
