/**
 * 3gpp-applying-bdt-policy
 * API for applying BDT policy © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * AppliedBDTPolicySubscriptionApiImpl.h
 *
 *
 */

#ifndef APPLIED_BDT_POLICY_SUBSCRIPTION_API_IMPL_H_
#define APPLIED_BDT_POLICY_SUBSCRIPTION_API_IMPL_H_

#include <AppliedBDTPolicySubscriptionApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <memory>
#include <optional>
#include <string>

#include "AppliedBdtPolicy.h"
#include "ProblemDetails.h"

namespace oai::nef::api {

using namespace oai::nef::model;

class AppliedBDTPolicySubscriptionApiImpl
    : public oai::nef::api::AppliedBDTPolicySubscriptionApi {
 public:
  explicit AppliedBDTPolicySubscriptionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~AppliedBDTPolicySubscriptionApiImpl() override = default;

  void af_id_subscriptions_get(
      const std::string& afId, Pistache::Http::ResponseWriter& response);
  void af_id_subscriptions_post(
      const std::string& afId, const AppliedBdtPolicy& appliedBdtPolicy,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
