/**
 * 3gpp-nidd-configuration-trigger
 * API for NIDD Configuration Trigger. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * DefaultApiImpl.h
 *
 *
 */

#ifndef DEFAULT_API_IMPL_H_
#define DEFAULT_API_IMPL_H_

#include <DefaultApi.h>
#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>

#include <memory>
#include <optional>
#include <string>

#include "NiddConfigurationTrigger.h"
#include "NiddConfigurationTriggerReply.h"
#include "ProblemDetails.h"

namespace oai::nef::api {

using namespace oai::nef::model;

class DefaultApiImpl : public oai::nef::api::DefaultApi {
 public:
  explicit DefaultApiImpl(const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~DefaultApiImpl() override = default;

  void root_post(
      const NiddConfigurationTrigger& niddConfigurationTrigger,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
