/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IndividualAnalyticsExposureSubscriptionApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

IndividualAnalyticsExposureSubscriptionApiImpl::
    IndividualAnalyticsExposureSubscriptionApiImpl(
        const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : IndividualAnalyticsExposureSubscriptionApi(rtr) {}

void IndividualAnalyticsExposureSubscriptionApiImpl::
    af_id_subscriptions_subscription_id_delete(
        const std::string& afId, const std::string& subscriptionId,
        Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void IndividualAnalyticsExposureSubscriptionApiImpl::
    af_id_subscriptions_subscription_id_get(
        const std::string& afId, const std::string& subscriptionId,
        const std::optional<std::string>& suppFeat,
        Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void IndividualAnalyticsExposureSubscriptionApiImpl::
    af_id_subscriptions_subscription_id_put(
        const std::string& afId, const std::string& subscriptionId,
        const AnalyticsExposureSubsc& analyticsExposureSubsc,
        Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
