/**
 * 3gpp-iptvconfiguration
 * API for IPTV configuration. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IPTVConfigurationsApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

IPTVConfigurationsApiImpl::IPTVConfigurationsApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : IPTVConfigurationsApi(rtr) {}

void IPTVConfigurationsApiImpl::af_id_configurations_get(
    const std::string& afId, Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}
void IPTVConfigurationsApiImpl::af_id_configurations_post(
    const std::string& afId, const IptvConfigData& iptvConfigData,
    Pistache::Http::ResponseWriter& response) {
  response.send(
      Pistache::Http::Code::Ok, "This API has not been implemented yet!\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
