/**
 * Common Data Types
 * Common Data Types for Service Based Interfaces. © 2020, 3GPP Organizational
 * Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "TwapIdRm.h"
#include "Helpers.h"

#include <sstream>

namespace oai::model::common {

TwapIdRm::TwapIdRm() {
  m_SsId              = "";
  m_SsIdIsSet         = false;
  m_BssId             = "";
  m_BssIdIsSet        = false;
  m_CivicAddressIsSet = false;
}

void TwapIdRm::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw oai::model::common::helpers::ValidationException(msg.str());
  }
}

bool TwapIdRm::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool TwapIdRm::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "TwapIdRm" : pathPrefix;

  return success;
}

bool TwapIdRm::operator==(const TwapIdRm& rhs) const {
  return

      ((!ssIdIsSet() && !rhs.ssIdIsSet()) ||
       (ssIdIsSet() && rhs.ssIdIsSet() && getSsId() == rhs.getSsId())) &&

      ((!bssIdIsSet() && !rhs.bssIdIsSet()) ||
       (bssIdIsSet() && rhs.bssIdIsSet() && getBssId() == rhs.getBssId())) &&

      ((!civicAddressIsSet() && !rhs.civicAddressIsSet()) ||
       (civicAddressIsSet() && rhs.civicAddressIsSet() &&
        getCivicAddress() == rhs.getCivicAddress()))

          ;
}

bool TwapIdRm::operator!=(const TwapIdRm& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const TwapIdRm& o) {
  j = nlohmann::json();
  if (o.ssIdIsSet()) j["ssId"] = o.m_SsId;
  if (o.bssIdIsSet()) j["bssId"] = o.m_BssId;
  if (o.civicAddressIsSet()) j["civicAddress"] = o.m_CivicAddress;
}

void from_json(const nlohmann::json& j, TwapIdRm& o) {
  if (j.find("ssId") != j.end()) {
    j.at("ssId").get_to(o.m_SsId);
    o.m_SsIdIsSet = true;
  }
  if (j.find("bssId") != j.end()) {
    j.at("bssId").get_to(o.m_BssId);
    o.m_BssIdIsSet = true;
  }
  if (j.find("civicAddress") != j.end()) {
    j.at("civicAddress").get_to(o.m_CivicAddress);
    o.m_CivicAddressIsSet = true;
  }
}

std::string TwapIdRm::getSsId() const {
  return m_SsId;
}
void TwapIdRm::setSsId(std::string const& value) {
  m_SsId      = value;
  m_SsIdIsSet = true;
}
bool TwapIdRm::ssIdIsSet() const {
  return m_SsIdIsSet;
}
void TwapIdRm::unsetSsId() {
  m_SsIdIsSet = false;
}
std::string TwapIdRm::getBssId() const {
  return m_BssId;
}
void TwapIdRm::setBssId(std::string const& value) {
  m_BssId      = value;
  m_BssIdIsSet = true;
}
bool TwapIdRm::bssIdIsSet() const {
  return m_BssIdIsSet;
}
void TwapIdRm::unsetBssId() {
  m_BssIdIsSet = false;
}
std::string TwapIdRm::getCivicAddress() const {
  return m_CivicAddress;
}
void TwapIdRm::setCivicAddress(std::string const& value) {
  m_CivicAddress      = value;
  m_CivicAddressIsSet = true;
}
bool TwapIdRm::civicAddressIsSet() const {
  return m_CivicAddressIsSet;
}
void TwapIdRm::unsetCivicAddress() {
  m_CivicAddressIsSet = false;
}

}  // namespace oai::model::common
