version: '3.8'
services:
    mysql:
        container_name: "mysql"
        image: mysql:5.7
        volumes:
            - ./oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_cp:
                ipv4_address: 192.168.71.131
    oai-nrf:
        container_name: "oai-nrf"
        image: oai-nrf:latest
        environment:
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=8080
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            public_net_cp:
                ipv4_address: 192.168.71.130
    oai-amf:
        container_name: "oai-amf"
        image: oai-amf:latest
        environment:
            - TZ=Europe/paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            - SST_0=222
            - SD_0=123
            - SST_1=1
            - SD_1=12
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai-smf
            - SMF_IPV4_ADDR_0=192.168.71.133
            - SMF_HTTP_VERSION_0=v1
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=oai-smf
            - SMF_IPV4_ADDR_1=0.0.0.0
            - SMF_HTTP_VERSION_1=v1
            - MYSQL_SERVER=192.168.71.131
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - OPERATOR_KEY=63bfa50ee6523365ff14c1f45f88737d
            - NRF_IPV4_ADDRESS=0.0.0.0
            - NRF_PORT=80
            - NF_REGISTRATION=no
            - SMF_SELECTION=no
            - USE_FQDN_DNS=no 
            - NRF_FQDN=oai-nrf
            - NRF_API_VERSION=v1
            - EXTERNAL_AUSF=no
            - AUSF_IPV4_ADDRESS=127.0.0.1
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
            - AUSF_FQDN=localhost
        depends_on:
            - mysql
            - vpp-upf
            - oai-ext-dn
        networks:
            public_net_cp:
                ipv4_address: 192.168.71.132
    oai-smf:
        container_name: "oai-smf"
        image: oai-smf:latest
        environment:
            - TZ=Europe/Paris
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=192.168.18.129
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_FQDN=oai-amf
            - AMF_IPV4_ADDRESS=192.168.71.132
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - UDM_IPV4_ADDRESS=127.0.0.1
            - UDM_FQDN=localhost
            - UDM_PORT=80
            - UDM_API_VERSION=v1
            - UPF_FQDN_0=vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - UPF_IPV4_ADDRESS=192.168.71.201
            - NRF_FQDN=oai-nrf
            - NRF_IPV4_ADDRESS=0.0.0.0
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - REGISTER_NRF=no
            - DISCOVER_UPF=no
            - USE_NETWORK_INSTANCE=yes
            - USE_FQDN_DNS=no
        extra_hosts:
            - "vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.71.201"
        depends_on:
            - oai-amf
        networks:
            public_net_cp:
                ipv4_address: 192.168.71.133
    vpp-upf:
        image: oai-upf-vpp:latest
        privileged: true
        container_name: "vpp-upf"
        environment:
            - IF_1_IP=192.168.71.201
            - IF_1_TYPE=N4
            - IF_2_IP=192.168.72.201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.oai.org
            - IF_3_IP=192.168.73.201
            - IF_3_TYPE=N6
            - IF_3_IP_REMOTE=192.168.73.135 # EXT-DN IP Address
            - IF_3_NWI=internet.oai.org
            - NAME=VPP-UPF
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=222
            - SNSSAI_SST=123
            - DNN=default
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=192.168.71.130
            - NRF_PORT=8080
            - HTTP_VERSION=2
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_cp:
                ipv4_address: 192.168.71.134
            public_net_access:
                ipv4_address: 192.168.72.134
            public_net_core:
                ipv4_address: 192.168.73.134
    oai-ext-dn:
        image: trf-gen-cn5g:latest
        privileged: true
        container_name: "oai-ext-dn"
        entrypoint: [ "/bin/bash", "-c", "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; \
                    ip route add 12.1.1.0/24 via 192.168.73.201 dev eth0; \
                    trap : TERM INT; sleep infinity & wait;
                    " ]
        depends_on:
            - vpp-upf
        healthcheck:
            test: /bin/bash -c "iptables -L -t nat | grep MASQUERADE"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net_core:
                ipv4_address: 192.168.73.135
networks:
    public_net_cp:
        name: oai-public-cp
        ipam:
            config:
                - subnet: 192.168.71.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-public"
    public_net_access:
        name: oai-public-access
        ipam:
            config:
                - subnet: 192.168.72.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-access"
    public_net_core:
        name: oai-public-core
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cn5g-core"
